@ECHO OFF
md "..\Packages\Magnesium"

RMDIR /S /Q ".\Debug\"
RMDIR /S /Q ".\Release\"
RMDIR /S /Q ".\x64\"
RMDIR /S /Q ".\Win32\"
RMDIR /S /Q ".\examples\x64\"
RMDIR /S /Q ".\examples\Win32\"
RMDIR /S /Q ".\examples\LD34\x64\"
RMDIR /S /Q ".\examples\LD34\Win32\"
RMDIR /S /Q ".\examples\Testbed\x64\"
RMDIR /S /Q ".\examples\Testbed\Win32\"
RMDIR /S /Q ".\Magnesium\x64\"
RMDIR /S /Q ".\Magnesium\Win32\"
DEL /F /S /Q *.log *.exp *.idb *.ilk *.iobj *.ipdb *.metagen *.pch
DEL /F /Q ".\bin\Testbed*.lib"
DEL /F /Q ".\bin32\Testbed*.lib"
DEL /F /Q ".\bin\Testbed*.pdb"
DEL /F /Q ".\bin32\Testbed*.pdb"
DEL /F /Q ".\bin\LD34*.lib"
DEL /F /Q ".\bin32\LD34*.lib"
DEL /F /Q ".\bin\LD34*.pdb"
DEL /F /Q ".\bin32\LD34*.pdb"
XCOPY *.* "..\Packages\Magnesium" /S /C /I /R /Y
DEL /F /Q "..\Packages\Magnesium\bin\D3D*.dll"
DEL /F /Q "..\Packages\Magnesium\bin\D3D*.pdb"
DEL /F /Q "..\Packages\Magnesium\bin32\D3D*.dll"
DEL /F /Q "..\Packages\Magnesium\bin32\D3D*.pdb"
DEL /F /S /Q "..\Packages\Magnesium\*.zip"
